packages:
  - apps/*
  - packages/*
  - tooling/*
  - backend
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: 5.8.3
  "@types/node": 22.15.29
  zod: ^3.25.49
  "@tanstack/react-query": 5.80.5
  "@tanstack/react-form": 1.12.2
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": 19.1.6
  "@types/react-dom": 19.1.5
  better-auth: 1.2.9
  vite: 6.3.5
  superjson: 2.2.2
  "@vitejs/plugin-react": 4.3.4
  "@tailwindcss/vite": 4.0.15
  "@tanstack/react-query-devtools": 5.80.5
  "@tanstack/react-router": 1.124.0
  "@tanstack/router-plugin": 1.121.2
  "@tanstack/react-router-devtools": 1.121.2
  "@tanstack/react-router-with-query": 1.121.2
  "@tanstack/react-start": 1.121.2
onlyBuiltDependencies:
  - esbuild
