packages:
  - apps/*
  - packages/*
  - tooling/*

cleanupUnusedCatalogs: true
minimumReleaseAge: 2880 # 2 days in minutes

catalog:
  "@better-auth/expo": 1.3.9
  "@orpc/client": 1.6.6
  "@orpc/server": 1.6.6
  "@orpc/tanstack-query": 1.6.6
  "@rocicorp/zero": 0.23.2025090100
  "@tailwindcss/vite": 4.1.8
  "@tanstack/react-form": 1.18.0
  "@tanstack/react-query": 5.84.2
  "@tanstack/react-query-devtools": 5.80.5
  "@tanstack/react-router": 1.131.2
  "@tanstack/react-router-devtools": 1.131.2
  "@tanstack/react-router-with-query": 1.130.17
  "@tanstack/react-start": 1.131.2
  "@tanstack/router-plugin": 1.131.2
  "@types/node": 22.15.29
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": 4.5.1
  better-auth: 1.3.9
  class-variance-authority: 0.7.1
  date-fns: 4.1.0
  clsx: ^2.1.1
  eslint: 9.35.0
  lucide-react: 0.525.0
  nanoid: 5.1.5
  next-themes: 0.4.6
  prettier: 3.6.2
  react: 19.0.0
  react-cookie: 8.0.1
  react-dom: 19.0.0
  sonner: 2.0.3
  superjson: 2.2.2
  tw-animate-css: 1.3.4
  typescript: 5.9.2
  typescript-eslint: 8.40.0
  vite: 6.3.5
  vite-tsconfig-paths: 5.1.4
  zod: 4.0.5
