packages:
  - apps/*
  - packages/*
  - tooling/*
  - backend
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: 5.8.3
  "@types/node": 22.15.29
  zod: ^3.25.49
  "@tanstack/react-query": 5.80.2
  "@tanstack/react-form": 1.12.2
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": 19.1.6
  "@types/react-dom": 19.1.5
  better-auth: 1.2.9
onlyBuiltDependencies:
  - esbuild
