packages:
  - apps/*
  - packages/*
  - tooling/*
  - backend

catalog:
  "@better-auth/expo": 1.3.3
  "@orpc/client": ^1.5.0
  "@orpc/server": ^1.5.0
  "@orpc/tanstack-query": ^1.5.0
  "@tailwindcss/vite": 4.1.8
  "@tanstack/react-query": 5.81.5
  "@tanstack/react-form": 1.14.0
  "@tanstack/react-query-devtools": 5.80.5
  "@tanstack/react-router": 1.127.9
  "@tanstack/react-router-with-query": 1.127.9
  "@tanstack/react-start": 1.127.9
  "@tanstack/router-plugin": 1.127.9
  "@types/node": 22.15.29
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": 4.5.1
  better-auth: 1.3.3
  clsx: ^2.1.1
  class-variance-authority: 0.7.1
  eslint: 9.28.0
  lucide-react: ^0.525.0
  next-themes: 0.4.6
  prettier: 3.6.2
  react: 19.0.0
  react-dom: 19.0.0
  sonner: 2.0.3
  superjson: 2.2.2
  typescript: 5.8.3
  tw-animate-css: 1.3.4
  vite: 6.3.5
  zod: 4.0.5

onlyBuiltDependencies:# TODO: I cant remember why I added this?
  - esbuild
