packages:
  - apps/*
  - packages/*
  - tooling/*
  - backend
catalog:
  "@vitejs/plugin-react": 4.3.4
  "@tailwindcss/vite": 4.0.15
  "@tanstack/react-query": 5.80.5
  "@tanstack/react-form": 1.14.0
  "@tanstack/react-query-devtools": 5.80.5
  "@tanstack/react-router": 1.124.0
  "@tanstack/router-plugin": 1.121.2
  "@tanstack/react-router-devtools": 1.121.2
  "@tanstack/react-router-with-query": 1.121.2
  "@tanstack/react-start": 1.121.2
  "@types/node": 22.15.29
  "@types/react": 19.1.6
  "@types/react-dom": 19.1.5
  eslint: ^9.28.0
  class-variance-authority: 0.7.1
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: 5.8.3
  zod: ^3.25.49
  react: 19.0.0
  react-dom: 19.0.0
  better-auth: 1.2.9
  vite: 6.3.5
  superjson: 2.2.2
  lucide-react: 0.475.0
  clsx: 2.1.1
  tw-animate-css: 1.3.4
  next-themes: 0.4.6
onlyBuiltDependencies:
  - esbuild
