/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema/index";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    accounts: {
      name: "accounts",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "id"
          >,
        },
        accountId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "accountId"
          >,
          serverName: "account_id",
        },
        providerId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "providerId"
          >,
          serverName: "provider_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "userId"
          >,
          serverName: "user_id",
        },
        accessToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "accessToken"
          >,
          serverName: "access_token",
        },
        refreshToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "refreshToken"
          >,
          serverName: "refresh_token",
        },
        idToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "idToken"
          >,
          serverName: "id_token",
        },
        accessTokenExpiresAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "accessTokenExpiresAt"
          >,
          serverName: "access_token_expires_at",
        },
        refreshTokenExpiresAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "refreshTokenExpiresAt"
          >,
          serverName: "refresh_token_expires_at",
        },
        scope: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "scope"
          >,
        },
        password: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "password"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "accounts",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    album: {
      name: "album",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "album",
            "id"
          >,
        },
        artistId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "album",
            "artistId"
          >,
          serverName: "artist_id",
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "album",
            "title"
          >,
        },
        year: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "album",
            "year"
          >,
        },
      },
      primaryKey: ["id"],
    },
    artist: {
      name: "artist",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "name"
          >,
        },
        sortName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "sortName"
          >,
          serverName: "sort_name",
        },
        type: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "type"
          >,
        },
        beginDate: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "beginDate"
          >,
          serverName: "begin_date",
        },
        endDate: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "endDate"
          >,
          serverName: "end_date",
        },
        popularity: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "artist",
            "popularity"
          >,
        },
      },
      primaryKey: ["id"],
    },
    attachments: {
      name: "attachments",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "id"
          >,
        },
        messageId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "messageId"
          >,
          serverName: "message_id",
        },
        fileName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "fileName"
          >,
          serverName: "file_name",
        },
        fileSize: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "fileSize"
          >,
          serverName: "file_size",
        },
        mimeType: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "mimeType"
          >,
          serverName: "mime_type",
        },
        url: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "url"
          >,
        },
        thumbnailUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "thumbnailUrl"
          >,
          serverName: "thumbnail_url",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachments",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    cartItem: {
      name: "cartItem",
      columns: {
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "cartItem",
            "userId"
          >,
          serverName: "user_id",
        },
        albumId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "cartItem",
            "albumId"
          >,
          serverName: "album_id",
        },
        addedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "cartItem",
            "addedAt"
          >,
          serverName: "added_at",
        },
      },
      primaryKey: ["userId", "albumId"],
      serverName: "cart_item",
    },
    chatUsers: {
      name: "chatUsers",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "userId"
          >,
          serverName: "user_id",
        },
        email: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "email"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "name"
          >,
        },
        sessionId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "sessionId"
          >,
          serverName: "session_id",
        },
        userAgent: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "userAgent"
          >,
          serverName: "user_agent",
        },
        ipAddress: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "ipAddress"
          >,
          serverName: "ip_address",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "createdAt"
          >,
          serverName: "created_at",
        },
        lastSeenAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "chatUsers",
            "lastSeenAt"
          >,
          serverName: "last_seen_at",
        },
      },
      primaryKey: ["id"],
      serverName: "chat_users",
    },
    conversationAssignments: {
      name: "conversationAssignments",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "id"
          >,
        },
        conversationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "conversationId"
          >,
          serverName: "conversation_id",
        },
        agentId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "agentId"
          >,
          serverName: "agent_id",
        },
        assignedBy: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "assignedBy"
          >,
          serverName: "assigned_by",
        },
        assignedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "assignedAt"
          >,
          serverName: "assigned_at",
        },
        unassignedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "unassignedAt"
          >,
          serverName: "unassigned_at",
        },
        reason: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversationAssignments",
            "reason"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "conversation_assignments",
    },
    conversations: {
      name: "conversations",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        chatUserId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "chatUserId"
          >,
          serverName: "chat_user_id",
        },
        assignedAgentId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "assignedAgentId"
          >,
          serverName: "assigned_agent_id",
        },
        status: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "status"
          >,
        },
        priority: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "priority"
          >,
        },
        subject: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "subject"
          >,
        },
        tags: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "tags"
          >,
        },
        pageUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "pageUrl"
          >,
          serverName: "page_url",
        },
        referrer: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "referrer"
          >,
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        closedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "conversations",
            "closedAt"
          >,
          serverName: "closed_at",
        },
      },
      primaryKey: ["id"],
    },
    invitations: {
      name: "invitations",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "email"
          >,
        },
        role: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "role"
          >,
        },
        teamId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "teamId"
          >,
          serverName: "team_id",
        },
        status: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "status"
          >,
        },
        expiresAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        inviterId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "invitations",
            "inviterId"
          >,
          serverName: "inviter_id",
        },
      },
      primaryKey: ["id"],
    },
    jwkss: {
      name: "jwkss",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "jwkss",
            "id"
          >,
        },
        publicKey: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "jwkss",
            "publicKey"
          >,
          serverName: "public_key",
        },
        privateKey: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "jwkss",
            "privateKey"
          >,
          serverName: "private_key",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "jwkss",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    members: {
      name: "members",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "members",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "members",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "members",
            "userId"
          >,
          serverName: "user_id",
        },
        role: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "members",
            "role"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "members",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    messages: {
      name: "messages",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "id"
          >,
        },
        conversationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "conversationId"
          >,
          serverName: "conversation_id",
        },
        senderId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "senderId"
          >,
          serverName: "sender_id",
        },
        senderType: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "senderType"
          >,
          serverName: "sender_type",
        },
        content: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "content"
          >,
        },
        messageType: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "messageType"
          >,
          serverName: "message_type",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "metadata"
          >,
        },
        isRead: {
          type: "boolean",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "isRead"
          >,
          serverName: "is_read",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "createdAt"
          >,
          serverName: "created_at",
        },
        editedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "editedAt"
          >,
          serverName: "edited_at",
        },
      },
      primaryKey: ["id"],
    },
    organizations: {
      name: "organizations",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "name"
          >,
        },
        slug: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "slug"
          >,
        },
        logo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "logo"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "createdAt"
          >,
          serverName: "created_at",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "metadata"
          >,
        },
      },
      primaryKey: ["id"],
    },
    sessions: {
      name: "sessions",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "id"
          >,
        },
        expiresAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "token"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        ipAddress: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "ipAddress"
          >,
          serverName: "ip_address",
        },
        userAgent: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "userAgent"
          >,
          serverName: "user_agent",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "userId"
          >,
          serverName: "user_id",
        },
        activeOrganizationId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "activeOrganizationId"
          >,
          serverName: "active_organization_id",
        },
        activeTeamId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "sessions",
            "activeTeamId"
          >,
          serverName: "active_team_id",
        },
      },
      primaryKey: ["id"],
    },
    teamMembers: {
      name: "teamMembers",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMembers",
            "id"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMembers",
            "teamId"
          >,
          serverName: "team_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMembers",
            "userId"
          >,
          serverName: "user_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMembers",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "team_members",
    },
    teams: {
      name: "teams",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teams",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teams",
            "name"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teams",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teams",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teams",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "name"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "email"
          >,
        },
        emailVerified: {
          type: "boolean",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "emailVerified"
          >,
          serverName: "email_verified",
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "image"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    verifications: {
      name: "verifications",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "id"
          >,
        },
        identifier: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "identifier"
          >,
        },
        value: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "value"
          >,
        },
        expiresAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verifications",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    accounts: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    album: {
      artist: [
        {
          sourceField: ["artistId"],
          destField: ["id"],
          destSchema: "artist",
          cardinality: "one",
        },
      ],
      cartItems: [
        {
          sourceField: ["id"],
          destField: ["albumId"],
          destSchema: "cartItem",
          cardinality: "many",
        },
      ],
    },
    artist: {
      albums: [
        {
          sourceField: ["id"],
          destField: ["artistId"],
          destSchema: "album",
          cardinality: "many",
        },
      ],
    },
    attachments: {
      message: [
        {
          sourceField: ["messageId"],
          destField: ["id"],
          destSchema: "messages",
          cardinality: "one",
        },
      ],
    },
    cartItem: {
      album: [
        {
          sourceField: ["albumId"],
          destField: ["id"],
          destSchema: "album",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    chatUsers: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizations",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      conversations: [
        {
          sourceField: ["id"],
          destField: ["chatUserId"],
          destSchema: "conversations",
          cardinality: "many",
        },
      ],
    },
    conversationAssignments: {
      conversation: [
        {
          sourceField: ["conversationId"],
          destField: ["id"],
          destSchema: "conversations",
          cardinality: "one",
        },
      ],
      agent: [
        {
          sourceField: ["agentId"],
          destField: ["id"],
          destSchema: "members",
          cardinality: "one",
        },
      ],
      assignedByAgent: [
        {
          sourceField: ["assignedBy"],
          destField: ["id"],
          destSchema: "members",
          cardinality: "one",
        },
      ],
    },
    conversations: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizations",
          cardinality: "one",
        },
      ],
      chatUser: [
        {
          sourceField: ["chatUserId"],
          destField: ["id"],
          destSchema: "chatUsers",
          cardinality: "one",
        },
      ],
      assignedAgent: [
        {
          sourceField: ["assignedAgentId"],
          destField: ["id"],
          destSchema: "members",
          cardinality: "one",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["conversationId"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      assignments: [
        {
          sourceField: ["id"],
          destField: ["conversationId"],
          destSchema: "conversationAssignments",
          cardinality: "many",
        },
      ],
    },
    invitations: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizations",
          cardinality: "one",
        },
      ],
      inviter: [
        {
          sourceField: ["inviterId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    members: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizations",
          cardinality: "one",
        },
      ],
    },
    messages: {
      conversation: [
        {
          sourceField: ["conversationId"],
          destField: ["id"],
          destSchema: "conversations",
          cardinality: "one",
        },
      ],
      attachments: [
        {
          sourceField: ["id"],
          destField: ["messageId"],
          destSchema: "attachments",
          cardinality: "many",
        },
      ],
    },
    organizations: {
      members: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "members",
          cardinality: "many",
        },
      ],
      invitations: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "invitations",
          cardinality: "many",
        },
      ],
      teams: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "teams",
          cardinality: "many",
        },
      ],
    },
    sessions: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    teamMembers: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "teams",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    teams: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizations",
          cardinality: "one",
        },
      ],
      teamMembers: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "teamMembers",
          cardinality: "many",
        },
      ],
    },
    users: {
      cartItems: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "cartItem",
          cardinality: "many",
        },
      ],
      sessions: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "sessions",
          cardinality: "many",
        },
      ],
      accounts: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "accounts",
          cardinality: "many",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "members",
          cardinality: "many",
        },
      ],
      invitations: [
        {
          sourceField: ["id"],
          destField: ["inviterId"],
          destSchema: "invitations",
          cardinality: "many",
        },
      ],
      teamMembers: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "teamMembers",
          cardinality: "many",
        },
      ],
    },
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
