// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChirp(ctx context.Context, id uuid.UUID) error
	GetChirpById(ctx context.Context, id uuid.UUID) (Chirp, error)
	GetChirps(ctx context.Context) ([]Chirp, error)
	GetChirpsByUserId(ctx context.Context, userID uuid.UUID) ([]Chirp, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserFromRefreshToken(ctx context.Context, token string) (User, error)
	ResetUsers(ctx context.Context) error
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateUserEmailAndPassword(ctx context.Context, arg UpdateUserEmailAndPasswordParams) (User, error)
	UpgradeToChirpyRed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
